// Ghana administrative geography seed data: 16 regions, 261 MMDAs (Metropolitan/
// Municipal/District Assemblies) with their capital towns.
//
// Source: Wikipedia "Districts of Ghana" (raw wikitext, retrieved 2026-09-12),
// which itself aggregates GhanaDistricts.gov.gh (official Local Government
// Service district assembly pages) and Ghana Statistical Service 2010
// Population and Housing Census district analytical reports. Reflects the
// post-2021 boundary (Guan District inaugurated October 2021, bringing the
// national total to 261 MMDAs across 16 regions).
//
// This captures one authoritative town per district (its capital) - a
// deliberately bounded starting point, not an exhaustive settlement census.
// See db/seedGhanaLocations.ts for how this is imported and where additional
// towns/schools can be layered on top without a schema change.

export const GHANA_SOURCE_REFERENCE =
  "Wikipedia: Districts of Ghana (aggregating GhanaDistricts.gov.gh and Ghana Statistical Service 2010 census district reports), retrieved 2026-09-12";

export interface GhanaDistrictSeed {
  region: string;
  name: string;
  category: "Metropolitan" | "Municipal" | "District";
  capital: string;
  isRegionalCapital?: boolean;
}

export const GHANA_REGION_CAPITALS: Record<string, string> = {
  Ahafo: "Goaso",
  Ashanti: "Kumasi",
  Bono: "Sunyani",
  "Bono East": "Techiman",
  Central: "Cape Coast",
  Eastern: "Koforidua",
  "Greater Accra": "Accra",
  Northern: "Tamale",
  "North East": "Nalerigu",
  Oti: "Dambai",
  Savannah: "Damongo",
  "Upper East": "Bolgatanga",
  "Upper West": "Wa",
  Volta: "Ho",
  Western: "Sekondi-Takoradi",
  "Western North": "Sefwi Wiawso",
};

export const GHANA_DISTRICTS: GhanaDistrictSeed[] = [
  // Ahafo (6)
  { region: "Ahafo", name: "Asunafo North", category: "Municipal", capital: "Goaso", isRegionalCapital: true },
  { region: "Ahafo", name: "Asunafo South", category: "District", capital: "Kukuom" },
  { region: "Ahafo", name: "Asutifi North", category: "District", capital: "Kenyasi" },
  { region: "Ahafo", name: "Asutifi South", category: "District", capital: "Hwidiem" },
  { region: "Ahafo", name: "Tano North", category: "Municipal", capital: "Duayaw Nkwanta" },
  { region: "Ahafo", name: "Tano South", category: "Municipal", capital: "Bechem" },

  // Ashanti (43)
  { region: "Ashanti", name: "Adansi Asokwa", category: "District", capital: "Adansi Asokwa" },
  { region: "Ashanti", name: "Adansi North", category: "District", capital: "Fomena" },
  { region: "Ashanti", name: "Adansi South", category: "District", capital: "New Edubiase" },
  { region: "Ashanti", name: "Afigya-Kwabre North", category: "District", capital: "Boamang" },
  { region: "Ashanti", name: "Afigya-Kwabre South", category: "District", capital: "Kodie" },
  { region: "Ashanti", name: "Ahafo-Ano North", category: "Municipal", capital: "Tepa" },
  { region: "Ashanti", name: "Ahafo-Ano South East", category: "District", capital: "Adugyama" },
  { region: "Ashanti", name: "Ahafo-Ano South West", category: "District", capital: "Mankranso" },
  { region: "Ashanti", name: "Akrofuom", category: "District", capital: "Akrofuom" },
  { region: "Ashanti", name: "Amansie Central", category: "District", capital: "Jacobu" },
  { region: "Ashanti", name: "Amansie West", category: "District", capital: "Manso Nkwanta" },
  { region: "Ashanti", name: "Amansie South", category: "District", capital: "Manso Adubia" },
  { region: "Ashanti", name: "Asante-Akim Central", category: "Municipal", capital: "Konongo" },
  { region: "Ashanti", name: "Asante-Akim North", category: "District", capital: "Agogo" },
  { region: "Ashanti", name: "Asante-Akim South", category: "Municipal", capital: "Juaso" },
  { region: "Ashanti", name: "Asokore-Mampong", category: "Municipal", capital: "Asokore Mampong" },
  { region: "Ashanti", name: "Asokwa", category: "Municipal", capital: "Asokwa" },
  { region: "Ashanti", name: "Atwima-Kwanwoma", category: "District", capital: "Twedie" },
  { region: "Ashanti", name: "Atwima-Mponua", category: "District", capital: "Nyinahin" },
  { region: "Ashanti", name: "Atwima-Nwabiagya", category: "Municipal", capital: "Nkawie" },
  { region: "Ashanti", name: "Atwima-Nwabiagya North", category: "District", capital: "Barekese" },
  { region: "Ashanti", name: "Bekwai", category: "Municipal", capital: "Bekwai" },
  { region: "Ashanti", name: "Bosome Freho", category: "District", capital: "Asiwa" },
  { region: "Ashanti", name: "Bosomtwe", category: "District", capital: "Kuntanase" },
  { region: "Ashanti", name: "Ejisu", category: "Municipal", capital: "Ejisu" },
  { region: "Ashanti", name: "Ejura/Sekyedumase", category: "Municipal", capital: "Ejura" },
  { region: "Ashanti", name: "Juaben", category: "Municipal", capital: "Juaben" },
  { region: "Ashanti", name: "Kumasi", category: "Metropolitan", capital: "Kumasi", isRegionalCapital: true },
  { region: "Ashanti", name: "Kwabre East", category: "Municipal", capital: "Mamponteng" },
  { region: "Ashanti", name: "Kwadaso", category: "Municipal", capital: "Kwadaso" },
  { region: "Ashanti", name: "Mampong", category: "Municipal", capital: "Mampong" },
  { region: "Ashanti", name: "Obuasi East", category: "Municipal", capital: "Tutuka" },
  { region: "Ashanti", name: "Obuasi", category: "Municipal", capital: "Obuasi" },
  { region: "Ashanti", name: "Offinso", category: "Municipal", capital: "Offinso" },
  { region: "Ashanti", name: "Offinso North", category: "District", capital: "Akomadan" },
  { region: "Ashanti", name: "Oforikrom", category: "Municipal", capital: "Oforikrom" },
  { region: "Ashanti", name: "Old Tafo", category: "Municipal", capital: "Old Tafo" },
  { region: "Ashanti", name: "Sekyere Afram Plains", category: "District", capital: "Drobonso" },
  { region: "Ashanti", name: "Sekyere Central", category: "District", capital: "Nsuta" },
  { region: "Ashanti", name: "Sekyere East", category: "District", capital: "Effiduase" },
  { region: "Ashanti", name: "Sekyere Kumawu", category: "District", capital: "Kumawu" },
  { region: "Ashanti", name: "Sekyere South", category: "District", capital: "Agona" },
  { region: "Ashanti", name: "Suame", category: "Municipal", capital: "Suame" },

  // Bono (12)
  { region: "Bono", name: "Banda", category: "District", capital: "Banda Ahenkro" },
  { region: "Bono", name: "Berekum East", category: "Municipal", capital: "Berekum" },
  { region: "Bono", name: "Berekum West", category: "District", capital: "Jinijini" },
  { region: "Bono", name: "Dormaa Central", category: "Municipal", capital: "Dormaa Ahenkro" },
  { region: "Bono", name: "Dormaa East", category: "District", capital: "Wamfie" },
  { region: "Bono", name: "Dormaa West", category: "District", capital: "Nkrankwanta" },
  { region: "Bono", name: "Jaman North", category: "District", capital: "Sampa" },
  { region: "Bono", name: "Jaman South", category: "Municipal", capital: "Drobo" },
  { region: "Bono", name: "Sunyani", category: "Municipal", capital: "Sunyani", isRegionalCapital: true },
  { region: "Bono", name: "Sunyani West", category: "District", capital: "Odumase" },
  { region: "Bono", name: "Tain", category: "District", capital: "Nsawkaw" },
  { region: "Bono", name: "Wenchi", category: "Municipal", capital: "Wenchi" },

  // Bono East (11)
  { region: "Bono East", name: "Atebubu-Amantin", category: "Municipal", capital: "Atebubu" },
  { region: "Bono East", name: "Kintampo North", category: "Municipal", capital: "Kintampo" },
  { region: "Bono East", name: "Kintampo South", category: "District", capital: "Jema" },
  { region: "Bono East", name: "Nkoranza North", category: "District", capital: "Busunya" },
  { region: "Bono East", name: "Nkoranza South", category: "Municipal", capital: "Nkoranza" },
  { region: "Bono East", name: "Pru East", category: "District", capital: "Yeji" },
  { region: "Bono East", name: "Pru West", category: "District", capital: "Prang" },
  { region: "Bono East", name: "Sene East", category: "District", capital: "Kajaji" },
  { region: "Bono East", name: "Sene West", category: "District", capital: "Kwame Danso" },
  { region: "Bono East", name: "Techiman", category: "Municipal", capital: "Techiman", isRegionalCapital: true },
  { region: "Bono East", name: "Techiman North", category: "District", capital: "Tuobodom" },

  // Central (22)
  { region: "Central", name: "Abura/Asebu/Kwamankese", category: "District", capital: "Abura-Dunkwa" },
  { region: "Central", name: "Agona East", category: "District", capital: "Nsaba" },
  { region: "Central", name: "Agona West", category: "Municipal", capital: "Agona Swedru" },
  { region: "Central", name: "Ajumako/Enyan/Essiam", category: "District", capital: "Ajumako" },
  { region: "Central", name: "Asikuma/Odoben/Brakwa", category: "District", capital: "Breman Asikuma" },
  { region: "Central", name: "Assin Central", category: "Municipal", capital: "Assin Foso" },
  { region: "Central", name: "Assin North", category: "District", capital: "Assin Bereku" },
  { region: "Central", name: "Assin South", category: "District", capital: "Nsuaem Kyekyewere" },
  { region: "Central", name: "Awutu Senya East", category: "Municipal", capital: "Kasoa" },
  { region: "Central", name: "Awutu Senya West", category: "District", capital: "Awutu Breku" },
  { region: "Central", name: "Cape Coast", category: "Metropolitan", capital: "Cape Coast", isRegionalCapital: true },
  { region: "Central", name: "Effutu", category: "Municipal", capital: "Winneba" },
  { region: "Central", name: "Ekumfi", category: "District", capital: "Esakyir" },
  { region: "Central", name: "Gomoa East", category: "District", capital: "Potsin" },
  { region: "Central", name: "Gomoa Central", category: "District", capital: "Afransi" },
  { region: "Central", name: "Gomoa West", category: "District", capital: "Apam" },
  { region: "Central", name: "Komenda/Edina/Eguafo/Abirem", category: "Municipal", capital: "Elmina" },
  { region: "Central", name: "Mfantsiman", category: "Municipal", capital: "Saltpond" },
  { region: "Central", name: "Twifo Atti Morkwa", category: "District", capital: "Twifo Praso" },
  { region: "Central", name: "Twifo/Hemang/Lower Denkyira", category: "District", capital: "Hemang" },
  { region: "Central", name: "Upper Denkyira East", category: "Municipal", capital: "Dunkwa-on-Offin" },
  { region: "Central", name: "Upper Denkyira West", category: "District", capital: "Diaso" },

  // Eastern (33)
  { region: "Eastern", name: "Abuakwa North", category: "Municipal", capital: "Kukurantumi" },
  { region: "Eastern", name: "Abuakwa South", category: "Municipal", capital: "Kibi" },
  { region: "Eastern", name: "Achiase", category: "District", capital: "Achiase" },
  { region: "Eastern", name: "Akuapim North", category: "Municipal", capital: "Akropong" },
  { region: "Eastern", name: "Akuapim South", category: "District", capital: "Aburi" },
  { region: "Eastern", name: "Akyemansa", category: "District", capital: "Ofoase" },
  { region: "Eastern", name: "Asene Manso Akroso", category: "District", capital: "Manso" },
  { region: "Eastern", name: "Asuogyaman", category: "District", capital: "Atimpoku" },
  { region: "Eastern", name: "Atiwa East", category: "District", capital: "Anyinam" },
  { region: "Eastern", name: "Atiwa West", category: "District", capital: "Kwabeng" },
  { region: "Eastern", name: "Ayensuano", category: "District", capital: "Coaltar" },
  { region: "Eastern", name: "Birim Central", category: "Municipal", capital: "Akim Oda" },
  { region: "Eastern", name: "Birim North", category: "District", capital: "New Abirem" },
  { region: "Eastern", name: "Birim South", category: "District", capital: "Akim Swedru" },
  { region: "Eastern", name: "Denkyembour", category: "District", capital: "Akwatia" },
  { region: "Eastern", name: "Fanteakwa North", category: "District", capital: "Begoro" },
  { region: "Eastern", name: "Fanteakwa South", category: "District", capital: "Osino" },
  { region: "Eastern", name: "Kwaebibirem", category: "Municipal", capital: "Kade" },
  { region: "Eastern", name: "Kwahu Afram Plains North", category: "District", capital: "Donkorkrom" },
  { region: "Eastern", name: "Kwahu Afram Plains South", category: "District", capital: "Tease" },
  { region: "Eastern", name: "Kwahu East", category: "District", capital: "Abetifi" },
  { region: "Eastern", name: "Kwahu South", category: "District", capital: "Mpraeso" },
  { region: "Eastern", name: "Kwahu West", category: "Municipal", capital: "Nkawkaw" },
  { region: "Eastern", name: "Lower Manya Krobo", category: "Municipal", capital: "Krobo Odumase" },
  { region: "Eastern", name: "New Juaben North", category: "Municipal", capital: "Effiduase" },
  { region: "Eastern", name: "New Juaben South", category: "Municipal", capital: "Koforidua", isRegionalCapital: true },
  { region: "Eastern", name: "Nsawam Adoagyire", category: "Municipal", capital: "Nsawam" },
  { region: "Eastern", name: "Okere", category: "District", capital: "Adukrom" },
  { region: "Eastern", name: "Suhum", category: "Municipal", capital: "Suhum" },
  { region: "Eastern", name: "Upper Manya Krobo", category: "District", capital: "Asesewa" },
  { region: "Eastern", name: "Upper West Akim", category: "District", capital: "Adeiso" },
  { region: "Eastern", name: "West Akim", category: "Municipal", capital: "Asamankese" },
  { region: "Eastern", name: "Yilo-Krobo", category: "Municipal", capital: "Somanya" },

  // Greater Accra (29)
  { region: "Greater Accra", name: "Ablekuma Central", category: "Municipal", capital: "Lartebiokorshie" },
  { region: "Greater Accra", name: "Ablekuma North", category: "Municipal", capital: "Darkuman" },
  { region: "Greater Accra", name: "Ablekuma West", category: "Municipal", capital: "Dansoman" },
  { region: "Greater Accra", name: "Accra", category: "Metropolitan", capital: "Accra", isRegionalCapital: true },
  { region: "Greater Accra", name: "Ada East", category: "District", capital: "Ada Foah" },
  { region: "Greater Accra", name: "Ada West", category: "District", capital: "Sege" },
  { region: "Greater Accra", name: "Adenta", category: "Municipal", capital: "Adenta" },
  { region: "Greater Accra", name: "Ashaiman", category: "Municipal", capital: "Ashaiman" },
  { region: "Greater Accra", name: "Ayawaso Central", category: "Municipal", capital: "Kokomlemle" },
  { region: "Greater Accra", name: "Ayawaso East", category: "Municipal", capital: "Nima" },
  { region: "Greater Accra", name: "Ayawaso North", category: "Municipal", capital: "Accra New Town" },
  { region: "Greater Accra", name: "Ayawaso West", category: "Municipal", capital: "Dzorwulu" },
  { region: "Greater Accra", name: "Ga Central", category: "Municipal", capital: "Sowutuom" },
  { region: "Greater Accra", name: "Ga East", category: "Municipal", capital: "Abokobi" },
  { region: "Greater Accra", name: "Ga North", category: "Municipal", capital: "Amomole" },
  { region: "Greater Accra", name: "Ga South", category: "Municipal", capital: "Ngleshie Amanfro" },
  { region: "Greater Accra", name: "Ga West", category: "Municipal", capital: "Amasaman" },
  { region: "Greater Accra", name: "Korle-Klottey", category: "Municipal", capital: "Osu" },
  { region: "Greater Accra", name: "Kpone-Katamanso", category: "Municipal", capital: "Kpone" },
  { region: "Greater Accra", name: "Krowor", category: "Municipal", capital: "Nungua" },
  { region: "Greater Accra", name: "La-Dade-Kotopon", category: "Municipal", capital: "La" },
  { region: "Greater Accra", name: "La-Nkwantanang-Madina", category: "Municipal", capital: "Madina" },
  { region: "Greater Accra", name: "Ledzokuku", category: "Municipal", capital: "Teshie" },
  { region: "Greater Accra", name: "Ningo-Prampram", category: "District", capital: "Prampram" },
  { region: "Greater Accra", name: "Okaikwei North", category: "Municipal", capital: "Tesano" },
  { region: "Greater Accra", name: "Shai-Osudoku", category: "District", capital: "Dodowa" },
  { region: "Greater Accra", name: "Tema Metropolitan", category: "Metropolitan", capital: "Tema" },
  { region: "Greater Accra", name: "Tema West", category: "Municipal", capital: "Tema Community 18" },
  { region: "Greater Accra", name: "Weija Gbawe", category: "Municipal", capital: "Weija" },

  // Northern (16)
  { region: "Northern", name: "Gushegu", category: "Municipal", capital: "Gushegu" },
  { region: "Northern", name: "Karaga", category: "District", capital: "Karaga" },
  { region: "Northern", name: "Kpandai", category: "District", capital: "Kpandai" },
  { region: "Northern", name: "Kumbungu", category: "District", capital: "Kumbungu" },
  { region: "Northern", name: "Mion", category: "District", capital: "Sang" },
  { region: "Northern", name: "Nanton", category: "District", capital: "Nanton" },
  { region: "Northern", name: "Nanumba North", category: "Municipal", capital: "Bimbilla" },
  { region: "Northern", name: "Nanumba South", category: "District", capital: "Wulensi" },
  { region: "Northern", name: "Saboba", category: "District", capital: "Saboba" },
  { region: "Northern", name: "Sagnarigu", category: "Municipal", capital: "Sagnarigu" },
  { region: "Northern", name: "Savelugu", category: "Municipal", capital: "Savelugu" },
  { region: "Northern", name: "Tamale", category: "Metropolitan", capital: "Tamale", isRegionalCapital: true },
  { region: "Northern", name: "Tatale Sanguli", category: "District", capital: "Tatale" },
  { region: "Northern", name: "Tolon", category: "District", capital: "Tolon" },
  { region: "Northern", name: "Yendi", category: "Municipal", capital: "Yendi" },
  { region: "Northern", name: "Zabzugu", category: "District", capital: "Zabzugu" },

  // North East (6)
  { region: "North East", name: "Bunkpurugu Nyankpanduri", category: "District", capital: "Bunkpurugu" },
  { region: "North East", name: "Chereponi", category: "District", capital: "Chereponi" },
  { region: "North East", name: "East Mamprusi", category: "Municipal", capital: "Nalerigu", isRegionalCapital: true },
  { region: "North East", name: "Mamprugu Moagduri", category: "District", capital: "Yagaba" },
  { region: "North East", name: "West Mamprusi", category: "Municipal", capital: "Walewale" },
  { region: "North East", name: "Yunyoo-Nasuan", category: "District", capital: "Yunyoo" },

  // Oti (9)
  { region: "Oti", name: "Biakoye", category: "District", capital: "Nkonya Ahenkro" },
  { region: "Oti", name: "Guan", category: "District", capital: "Likpe-Mate" },
  { region: "Oti", name: "Jasikan", category: "Municipal", capital: "Jasikan" },
  { region: "Oti", name: "Kadjebi", category: "District", capital: "Kadjebi" },
  { region: "Oti", name: "Krachi East", category: "Municipal", capital: "Dambai", isRegionalCapital: true },
  { region: "Oti", name: "Krachi Nchumuru", category: "District", capital: "Chinderi" },
  { region: "Oti", name: "Krachi West", category: "Municipal", capital: "Kete Krachi" },
  { region: "Oti", name: "Nkwanta North", category: "District", capital: "Kpassa" },
  { region: "Oti", name: "Nkwanta South", category: "Municipal", capital: "Nkwanta" },

  // Savannah (7)
  { region: "Savannah", name: "Bole", category: "District", capital: "Bole" },
  { region: "Savannah", name: "Central Gonja", category: "District", capital: "Buipe" },
  { region: "Savannah", name: "East Gonja", category: "Municipal", capital: "Salaga" },
  { region: "Savannah", name: "North Gonja", category: "District", capital: "Daboya" },
  { region: "Savannah", name: "North East Gonja", category: "District", capital: "Kpalbe" },
  { region: "Savannah", name: "Sawla-Tuna-Kalba", category: "District", capital: "Sawla" },
  { region: "Savannah", name: "West Gonja", category: "Municipal", capital: "Damongo", isRegionalCapital: true },

  // Upper East (15)
  { region: "Upper East", name: "Bawku", category: "Municipal", capital: "Bawku" },
  { region: "Upper East", name: "Bawku West", category: "District", capital: "Zebilla" },
  { region: "Upper East", name: "Binduri", category: "District", capital: "Binduri" },
  { region: "Upper East", name: "Bolgatanga East", category: "District", capital: "Zuarungu" },
  { region: "Upper East", name: "Bolgatanga", category: "Municipal", capital: "Bolgatanga", isRegionalCapital: true },
  { region: "Upper East", name: "Bongo", category: "District", capital: "Bongo" },
  { region: "Upper East", name: "Builsa North", category: "Municipal", capital: "Sandema" },
  { region: "Upper East", name: "Builsa South", category: "District", capital: "Fumbisi" },
  { region: "Upper East", name: "Garu", category: "District", capital: "Garu" },
  { region: "Upper East", name: "Kassena-Nankana", category: "Municipal", capital: "Navrongo" },
  { region: "Upper East", name: "Kassena-Nankana West", category: "District", capital: "Paga" },
  { region: "Upper East", name: "Nabdam", category: "District", capital: "Nangodi" },
  { region: "Upper East", name: "Pusiga", category: "District", capital: "Pusiga" },
  { region: "Upper East", name: "Talensi", category: "District", capital: "Tongo" },
  { region: "Upper East", name: "Tempane", category: "District", capital: "Tempane" },

  // Upper West (11)
  { region: "Upper West", name: "Daffiama Bussie Issa", category: "District", capital: "Issa" },
  { region: "Upper West", name: "Jirapa", category: "Municipal", capital: "Jirapa" },
  { region: "Upper West", name: "Lambussie Karni", category: "District", capital: "Lambussie" },
  { region: "Upper West", name: "Lawra", category: "Municipal", capital: "Lawra" },
  { region: "Upper West", name: "Nadowli-Kaleo", category: "District", capital: "Nadowli" },
  { region: "Upper West", name: "Nandom", category: "Municipal", capital: "Nandom" },
  { region: "Upper West", name: "Sissala East", category: "Municipal", capital: "Tumu" },
  { region: "Upper West", name: "Sissala West", category: "District", capital: "Gwollu" },
  { region: "Upper West", name: "Wa East", category: "District", capital: "Funsi" },
  { region: "Upper West", name: "Wa", category: "Municipal", capital: "Wa", isRegionalCapital: true },
  { region: "Upper West", name: "Wa West", category: "District", capital: "Wechiau" },

  // Volta (18)
  { region: "Volta", name: "Adaklu", category: "District", capital: "Adaklu Waya" },
  { region: "Volta", name: "Afadzato South", category: "District", capital: "Ve Golokwati" },
  { region: "Volta", name: "Agotime Ziope", category: "District", capital: "Kpetoe" },
  { region: "Volta", name: "Akatsi North", category: "District", capital: "Ave-Dakpa" },
  { region: "Volta", name: "Akatsi South", category: "District", capital: "Akatsi" },
  { region: "Volta", name: "Anloga", category: "District", capital: "Anloga" },
  { region: "Volta", name: "Central Tongu", category: "District", capital: "Adidome" },
  { region: "Volta", name: "Ho", category: "Municipal", capital: "Ho", isRegionalCapital: true },
  { region: "Volta", name: "Ho West", category: "District", capital: "Dzolokpuita" },
  { region: "Volta", name: "Hohoe", category: "Municipal", capital: "Hohoe" },
  { region: "Volta", name: "Keta", category: "Municipal", capital: "Keta" },
  { region: "Volta", name: "Ketu North", category: "Municipal", capital: "Dzodze" },
  { region: "Volta", name: "Ketu South", category: "Municipal", capital: "Denu" },
  { region: "Volta", name: "Kpando", category: "Municipal", capital: "Kpando" },
  { region: "Volta", name: "North Dayi", category: "District", capital: "Anfoega" },
  { region: "Volta", name: "North Tongu", category: "District", capital: "Battor Dugame" },
  { region: "Volta", name: "South Dayi", category: "District", capital: "Kpeve" },
  { region: "Volta", name: "South Tongu", category: "District", capital: "Sogakope" },

  // Western (14)
  { region: "Western", name: "Ahanta West", category: "Municipal", capital: "Agona Ahanta" },
  { region: "Western", name: "Amenfi Central", category: "District", capital: "Manso Amenfi" },
  { region: "Western", name: "Amenfi West", category: "Municipal", capital: "Asankragua" },
  { region: "Western", name: "Effia Kwesimintsim", category: "Municipal", capital: "Kwesimintsim" },
  { region: "Western", name: "Ellembelle", category: "District", capital: "Nkroful" },
  { region: "Western", name: "Jomoro", category: "Municipal", capital: "Half Assini" },
  { region: "Western", name: "Mpohor", category: "District", capital: "Mpohor" },
  { region: "Western", name: "Nzema East", category: "Municipal", capital: "Axim" },
  { region: "Western", name: "Prestea-Huni Valley", category: "Municipal", capital: "Prestea" },
  { region: "Western", name: "Sekondi Takoradi", category: "Metropolitan", capital: "Sekondi-Takoradi", isRegionalCapital: true },
  { region: "Western", name: "Shama", category: "District", capital: "Shama" },
  { region: "Western", name: "Tarkwa-Nsuaem", category: "Municipal", capital: "Tarkwa" },
  { region: "Western", name: "Wassa Amenfi East", category: "Municipal", capital: "Wassa-Akropong" },
  { region: "Western", name: "Wassa East", category: "District", capital: "Daboase" },

  // Western North (9)
  { region: "Western North", name: "Aowin", category: "Municipal", capital: "Enchi" },
  { region: "Western North", name: "Bia East", category: "District", capital: "Sefwi Adabokrom" },
  { region: "Western North", name: "Bia West", category: "District", capital: "Essam-Debiso" },
  { region: "Western North", name: "Bibiani Anhwiaso Bekwai", category: "Municipal", capital: "Bibiani" },
  { region: "Western North", name: "Bodi", category: "District", capital: "Sefwi Bodi" },
  { region: "Western North", name: "Juaboso", category: "District", capital: "Juaboso" },
  { region: "Western North", name: "Sefwi Akontombra", category: "District", capital: "Sefwi Akontombra" },
  { region: "Western North", name: "Sefwi-Wiawso", category: "Municipal", capital: "Sefwi Wiawso", isRegionalCapital: true },
  { region: "Western North", name: "Suaman", category: "District", capital: "Dadieso" },
];
